### ISSUE TITLE
Suggestion: Class Stats

### ISSUE THREAD

**Issue by duralakun** [ResamVi/infclass-stats#13]
- Show how many kills a specific class has on average
- Show the max amounts of kills that a class reached in one round
- Show average survival time of a class

**Comment by ResamVi** [comment]
- [X] Show how many kills a specific class has on average
- [X] Show the max amounts of kills that a class reached in one round
- [ ] Show average survival time of a class (WIP)

**Comment by ResamVi** [comment]
dd4c6680a009d1ac225292de682ebd592578ee9f
