### ISSUE TITLE
High-Resolution map images

### ISSUE THREAD

**Issue by duralakun** [ResamVi/infclass-stats#14]
Right now one map image is 1600 x 875 pixels big.
But on the website it will be scaled down by a lot.
So I wonder if they could maybe be smaller like 800 x 438 for example.
In order to make the website load faster and save traffic.
Or is high resolution required?

**Comment by ResamVi** [comment]
asset folder 6.95MB =>0.99MB
a80869247ae36683f7529dfff514c700e5498fcb
