### ISSUE TITLE
Win in last round is not recorded

### ISSUE THREAD

**Issue by bretonium** [ResamVi/infclass-stats#4]
Survival in the last, 5th round is not being recorded to stats.

Steps to reproduce:
1. Say !me or !survivals and remember how many survivals you have
2. Win round 5/5
3. Say !me or !survivals in the next map - your survival counter will stay the same

**Comment by ResamVi** [comment]
I tried multiple times now but can't seem to reproduce this.

**Comment by bretonium** [comment]
Looks like it got fixed in https://github.com/ResamVi/infclass-stats/commit/bc18b2f1d70ce92a4bd98885af1a30ee889bef6e . Thank you!

Could you please explain why the delay is necessary?

**Comment by ResamVi** [comment]
So when the 5th stops a summary of each player's map performance is printed and all data is thrown out afterwards (this also includes which players are currently playing and their score).

However after the summary is printed there is still things to be calculated - the people that have survived - and this requires amongst other things the player names that previously have been thrown out too early.

The delay is a big bandaid fix to inherent problems concerning keeping a consistent state for the right times. The re-write is still in process.
