### ISSUE TITLE
Suggestion: Show how many people are currently online

### ISSUE THREAD

**Issue by duralakun** [ResamVi/infclass-stats#6]
For example if 7 people are online and 64 could join overall: 
CURRENTLY ONLINE - 7/64

**Comment by ResamVi** [comment]
I can't get access to the max client number. I won't assume it's always 64 so it'll probably be just "7 Players online"

**Comment by ResamVi** [comment]
8352440e5f754e31b4a2bae9e9f5e16089b88282 done
